name: Test
on: push

jobs:
  binder:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: update jupyter dependencies with repo2docker
      uses: jupyterhub/repo2docker-action@master
      with:
        DOCKER_USERNAME: ${{ secrets.prabhas75 }}
        DOCKER_PASSWORD: ${{ secrets.dckr_pat_x9WIf3G2ae3Q0J1xOgHSarfmtx8 }}
        BINDER_CACHE: true
        PUBLIC_REGISTRY_CHECK: true
